import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ActionItem {
  task: string;
  suggestedAssignee: string;
  status: string;
}

interface MeetingData {
  title: string;
  meetingCode: string;
  startTime: string;
  summary: string;
  sentiment: string;
  highlights: string[];
  actionItems: ActionItem[];
  transcript?: string;
}

export const generateMeetingReport = (meeting: MeetingData) => {
  const doc = new jsPDF();
  const date = new Date(meeting.startTime).toLocaleDateString();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(40, 44, 52);
  doc.text('IntellMeet Intelligence Report', 14, 20);
  
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text(`Meeting: ${meeting.title}`, 14, 30);
  doc.text(`Code: ${meeting.meetingCode} | Date: ${date}`, 14, 38);

  // Sentiment
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Overall Sentiment:', 14, 50);
  const sentimentColor = meeting.sentiment === 'positive' ? [34, 197, 94] : 
                        meeting.sentiment === 'negative' ? [239, 68, 68] : [100, 100, 100];
  // @ts-ignore
  doc.setTextColor(sentimentColor[0], sentimentColor[1], sentimentColor[2]);
  doc.text(meeting.sentiment.toUpperCase(), 55, 50);

  // Summary
  doc.setFontSize(14);
  doc.setTextColor(40, 44, 52);
  doc.text('Executive Summary', 14, 65);
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  const splitSummary = doc.splitTextToSize(meeting.summary, 180);
  doc.text(splitSummary, 14, 72);

  let currentY = 72 + (splitSummary.length * 5) + 10;

  // Highlights
  if (meeting.highlights && meeting.highlights.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(40, 44, 52);
    doc.text('Key Highlights', 14, currentY);
    currentY += 7;
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    meeting.highlights.forEach((h) => {
      doc.text(`• ${h}`, 14, currentY);
      currentY += 6;
    });
    currentY += 5;
  }

  // Action Items Table
  if (meeting.actionItems && meeting.actionItems.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(40, 44, 52);
    doc.text('Action Items', 14, currentY);
    
    autoTable(doc, {
      startY: currentY + 5,
      head: [['Task', 'Assignee', 'Status']],
      body: meeting.actionItems.map(item => [item.task, item.suggestedAssignee, item.status]),
      headStyles: { fillStyle: [37, 99, 235] },
    });
  }

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by IntellMeet AI - Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.height - 10);
  }

  doc.save(`IntellMeet_Report_${meeting.meetingCode}.pdf`);
};
