const fs = require('fs');
const path = require('path');

const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;

/**
 * Calls Gemini AI directly via REST API (Ultra-Stable v1)
 * @param {string} prompt - The text prompt to send
 * @param {string} model - Model identifier (default: gemini-1.5-flash)
 * @returns {Promise<string>} - AI Response text
 */
async function callGemini(prompt, model = "gemini-1.5-flash") {
    if (!GOOGLE_API_KEY) {
        throw new Error("AI Error: GOOGLE_API_KEY is missing in .env");
    }

    const url = `https://generativelanguage.googleapis.com/v1/models/${model}:generateContent?key=${GOOGLE_API_KEY}`;
    
    try {
        const response = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: prompt }]
                }]
            })
        });

        const data = await response.json();

        if (!response.ok) {
            const errorMsg = data.error?.message || response.statusText;
            throw new Error(`Google API Error: ${errorMsg} (${response.status})`);
        }

        if (!data.candidates || data.candidates.length === 0) {
            throw new Error("AI Error: No response generated by Gemini.");
        }

        return data.candidates[0].content.parts[0].text;
    } catch (error) {
        console.error('[AI_SERVICE] Gemini Direct Call Failed:', error.message);
        throw error;
    }
}

/**
 * Stub for transcription - Logic moved to client-side Web Speech API
 */
const transcribeAudio = async () => '';

/**
 * Generates meeting intelligence using Gemini REST API
 */
const generateMeetingIntelligence = async (transcript) => {
    try {
        if (!transcript) return null;

        const prompt = `You are a professional meeting assistant. Analyzing the following transcript, provide a concise summary and extract key action items with suggested assignees. Format your response strictly as a JSON object with keys "summary" (string) and "actionItems" (array of {task, user}).\n\nTranscript: ${transcript}`;
        
        const responseText = await callGemini(prompt);
        // Try to find and parse JSON block
        const jsonMatch = responseText.match(/\{[\s\S]*\}/);
        return JSON.parse(jsonMatch ? jsonMatch[0] : responseText);
    } catch (error) {
        console.error('[AI_SERVICE] Intelligence Generation Error:', error.message);
        return null;
    }
};

/**
 * Real-time AI Assistant response using Gemini REST API
 */
const getAIResponse = async (query, context) => {
    try {
        const maxContextChars = 20000;
        const truncatedContext = context && context.length > maxContextChars 
            ? "..." + context.substring(context.length - maxContextChars)
            : context;

        const prompt = `You are the IntellMeet AI Companion. Answer the user's question based on the provided meeting context. Be helpful, professional, and concise.\n\nContext: ${truncatedContext || "No transcript available yet."}\nUser Question: ${query}\nResponse:`;
        
        return await callGemini(prompt);
    } catch (error) {
        console.error('[AI_SERVICE] Chat Assistant Error:', error.message);
        return `AI Error: ${error.message}`;
    }
};

module.exports = {
    transcribeAudio,
    generateMeetingIntelligence,
    getAIResponse
};
